baseurl = "https://www.thanwarin.com/"
languageCode = 'en-us'
title = "3 : Thanwarin"

[[menus.main]]
name = 'About'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
