baseurl = "https://www.thanwarin.com/"
languageCode = 'en-us'
title = "3 : Thanwarin"

[[menus.main]]
name = 'About'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 2

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 3

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 4

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
